#+TITLE: Guix System Configuration
#+PROPERTY: header-args :mkdirp yes


* Guix Channels

Guix uses [[https://guix.gnu.org/manual/en/html_node/Channels.html][channels]]
which are basically git repositories containing Guile files
defining Guix packages that can be installed on your system.


** nonguix

As my current laptop uses a WiFi chip which doesn't have a
supported libre driver and Guix is a
[[https://www.gnu.org/distros/free-system-distribution-guidelines.html][free system]]
so we have to add the
[[https://gitlab.com/nonguix/nonguix][nonguix]] channel to use the non-free Linux kernel.

#+BEGIN_SRC scheme :tangle ../jayu/build/channels.scm
  (define nonguix
    (channel
      (name 'nonguix)
      (url "https://gitlab.com/nonguix/nonguix")
      (introduction
	(make-channel-introduction
	  "897c1a470da759236cc11798f4e0a5f7d4d59fbc"
	  (openpgp-fingerprint
	    "2A39 3FFF 68F4 EF7A 3D29  12AF 6F51 20A0 22FB B2D5")))))
#+END_SRC

Also add the [[https://substitutes.nonguix.org/signing-key.pub][signing key]] to sign the Nonguix substitute
server.

#+BEGIN_SRC scheme :tangle ../jayu/build/nonguix-key.pub
  (public-key
   (ecc
    (curve Ed25519)
    (q #C1FD53E5D4CE971933EC50C9F307AE2171A2D3B52C804642A7A35F84F3A4EA98#)))
#+END_SRC


** rde

[[https://git.sr.ht/~abcdw/rde][rde]] is an extension on top of Guix home which
adds additional services for configuring the home environment
and operating system.

#+BEGIN_SRC scheme :tangle ../jayu/build/channels.scm
  (define rde
    (channel
      (name 'rde)
      (url "https://git.sr.ht/~abcdw/rde")
      (introduction
	(make-channel-introduction
	  "257cebd587b66e4d865b3537a9a88cccd7107c95"
	  (openpgp-fingerprint
	    "2841 9AC6 5038 7440 C7E9  2FFA 2208 D209 58C1 DEB0")))))
#+END_SRC


** Base Channels

Return all the channels including the base channels which has
the main Guix channel.

#+BEGIN_SRC scheme :tangle ../jayu/build/channels.scm
  (cons* nonguix
	 rde
	 %default-channels)
#+END_SRC


* Base System

This configuration is (will be) shared between different
computers and as such they share the same base services,
packages, and system.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/base.scm
  (define-module (jayu build system base)
    #:use-module (gnu)
    #:use-module (gnu packages)
    #:use-module (gnu system)
    #:use-module (gnu packages bash)
    #:use-module (gnu packages shells))
#+END_SRC


** Packages

Define some basic system agnostic packages to include in all
machines.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/base.scm
    (define-public jayu-base-packages
      (append
	(map (compose list specification->package+output)
	'("curl" "dbus" "emacs" "gash" "git" "gnupg"
	  "guile-readline" "make" "ncurses" "nss-certs"
	  "openssh" "wget" "vim" "xdg-user-dirs" "xdg-utils"))
	%base-packages))
#+END_SRC


** Services

Define a service which adds coreutils to =/usr/bin/env=,
Bash to =/bin/bash=, and Dash to =/bin/sh=.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/base.scm
  (define-public jayu-file-services
    (list
      (extra-special-file "/usr/bin/env"
			  (file-append coreutils "/usr/bin/env"))
      (extra-special-file "/bin/zsh"
			  (file-append zsh "/bin/zsh"))
      (extra-special-file "/bin/bash"
			  (file-append bash "/bin/bash"))
      (extra-special-file "/bin/sh"
			  (file-append dash "/bin/dash"))))
#+END_SRC


** Users

Define a list of users which will be on all machines.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/base.scm
  (define jayu-users
    (list
      (user-account
       (name "nouun")
       (comment "nouun")
       (home-directory "/home/nouun")
       (group "users")
       (supplementary-groups
	 '("wheel" "netdev" "audio" "video"))
       (shell (file-append bash "/bin/bash")))))

  (define-public jayu-base-users
    (append
       jayu-users
       %base-user-accounts))
#+END_SRC


** Base System

Define a base system which is inherited and updated in each
specific machine configuration.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/base.scm
  (define-public jayu-base-system
    (operating-system
      (locale "en_NZ.utf8")
      (timezone "Pacific/Auckland")
      (host-name "guix")

      (users jayu-base-users)
      (packages jayu-base-packages)
      (services jayu-file-services)

      (bootloader
	(bootloader-configuration
	  (bootloader grub-efi-bootloader)
	  (targets (list "/boot/efi"))))

      ;; Guix requires file-system to be defined to create an operating-system
      ;; so pass through a dummy file system which will be overriden in each
      ;; machine configuration.
      (file-systems
	(cons* (file-system
		 (mount-point "/")
		 (device "none")
		 (type "ext4")
		 (check? #f))
	       %base-file-systems))))
#+END_SRC

* Machines


** Verrb (MacBook Pro)

Verrb is the configuration that is used on my Macbook Pro.
Being an Apple Macbook, it uses a nonfree WiFi chip and as
such, the non-free Linux kernel and b43 firmware are required
to get WiFi working.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/verrb.scm
  (define-module (jayu build system verrb)
    #:use-module (gnu)
    #:use-module (gnu packages bash)
    #:use-module (gnu packages firmware)
    #:use-module (gnu packages messaging)
    #:use-module (gnu system)
    #:use-module (gnu services desktop)
    #:use-module (gnu services dns)
    #:use-module (gnu services networking)
    #:use-module (gnu services messaging)
    #:use-module (gnu services sddm)
    #:use-module (gnu services ssh)
    #:use-module (gnu services web)
    #:use-module (gnu services xorg)
    #:use-module (guix store)
    #:use-module (guix gexp)
    #:use-module (srfi srfi-1)

    ; Nonfree packages: linux, b43-firmware 
    #:use-module (nongnu packages linux)
    #:use-module (jayu packages nonfree)

    #:use-module (jayu build system base)
    #:use-module (jayu packages display-managers)
    #:use-module (jayu packages extras)
    #:use-module (jayu packages rust-apps))
#+END_SRC


*** Packages

Define packages specific to Verrb. =alsa-utils= and
=pulseaudio= are used for audio. My AwesomeWM configuration
requires an upstream version, therefore =awesome-git= is used
instead of the packaged version included in the Guix repos.
=verrb-sddm-theme= is the SDDM theme that I made and use.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/verrb.scm
  (define verrb-packages
    (append
     (list awesome-git
	   adverrb-sddm-theme)
     (map (compose list specification->package+output)
	  '("alsa-utils" "pulseaudio"))
     jayu-base-packages))
#+END_SRC


*** Services

**** SDDM

This will install SDDM as the display manager and use the
verrb theme.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/verrb.scm
  (define verrb-sddm-service
    (service sddm-service-type
             (sddm-configuration
              (theme "verrb"))))
#+END_SRC


**** Bitlbee

Enable Bitlbee and install the Discord plugin so we can
interact with Discord without having to use the bloated
electron client.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/verrb.scm
  (define verrb-bitlbee-service
    (service bitlbee-service-type
	     (bitlbee-configuration
	       (plugins
	         (list bitlbee-discord)))))
#+END_SRC


**** Desktop Services

Modify the default desktop services to do the following:

1) Remove GDM as SDDM is used instead.
2) Set Guix to always use 4 cores.
3) Stop network-manager from modifying /etc/resolve.conf

To use the Nonguix substitute server, we need to modify
the guix service and add the substitute server as well as
the signing key.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/verrb.scm
  (define verrb-desktop-services
     (modify-services
       (remove (lambda (service)
		(eq? (service-kind service) gdm-service-type))
	   %desktop-services)

       (guix-service-type
	 config => (guix-configuration
		    (inherit config)
		    (extra-options '("--max-job=4"))
                    (substitute-urls
                     (append %default-substitute-urls
                       (list "https://substitutes.nonguix.org")))
                    (authorized-keys
                     (append %default-authorized-guix-keys
                       (list (local-file "../nonguix-key.pub"))))))

       (network-manager-service-type
	 config => (network-manager-configuration
		    (inherit config)
		    (dns "none")))))
#+END_SRC

**** Verrb Services

Append all services into a single list.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/verrb.scm
  (define verrb-services
    (append (list verrb-sddm-service
                  verrb-bitlbee-service)
            verrb-desktop-services
            jayu-file-services))
#+END_SRC


*** System


**** File System

Mount root and boot partitions.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/verrb.scm
  (define verrb-file-system
    (cons* (file-system
             (mount-point "/")
             (device
               (uuid "e66d5096-1a1a-420d-92f0-b01cf7d103ea"
                     'ext4))
             (type "ext4"))
           (file-system
             (mount-point "/boot/efi")
             (device (uuid "A23F-3C5F" 'fat32))
             (type "vfat"))
           %base-file-systems))
#+END_SRC


**** System

Return a new operating system which inherits the
=jayu-base-system= created in the base configuration and
passes through the variables we've already defined. As
mentioned at the start, this machine requires the
non-free Linux kernel and b43-firmware so we also set
those.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/verrb.scm
  (operating-system
    (inherit jayu-base-system)
    (host-name "verrb")
    (users jayu-base-users)
    (file-systems verrb-file-system)
  
    (packages verrb-packages)
    (services verrb-services)

    (kernel linux)
    (firmware (list b43-firmware)))
#+END_SRC


** Pronouun (Server)

Pronouun is the configuration that is used on the server which
hosts my website and git frontend.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/pronouun.scm
  (define-module (jayu build system pronouun)
    #:use-module (gnu)
    #:use-module (gnu packages bash)
    #:use-module (gnu packages firmware)
    #:use-module (gnu packages messaging)
    #:use-module (gnu system)
    #:use-module (gnu services dns)
    #:use-module (gnu services networking)
    #:use-module (gnu services messaging)
    #:use-module (gnu services ssh)
    #:use-module (gnu services web)
    #:use-module (guix store)
    #:use-module (srfi srfi-1)
    #:use-module (jayu build system base))
#+END_SRC

*** Packages

Define packages specific to Pronouun.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/pronouun.scm
  (use-package-modules certs tls)
  
  (define pronouun-packages
    (append
     (list nss-certs
	   certbot)
     jayu-base-packages))
#+END_SRC


*** Services

Mainly just git and website services

**** Git Daemon

Git Daemon

#+BEGIN_SRC scheme :tangle ../jayu/build/system/pronouun.scm
  (use-service-modules version-control)
  
  (define pronouun-git-daemon-service
    (service git-daemon-service-type))
;	     (git-daemon-configuration)))
;	      (base-path "/home/git/repositories/"))))
#+END_SRC


**** FastCGI

Fast CGI

#+BEGIN_SRC scheme :tangle ../jayu/build/system/pronouun.scm
  (define pronouun-fcgi-service
    (service fcgiwrap-service-type))
#+END_SRC


**** Cgit

Git frontend

#+BEGIN_SRC scheme :tangle ../jayu/build/system/pronouun.scm
  (use-service-modules cgit)
  (use-package-modules version-control)

  (define (cert-path host file)
    (format #f "/etc/letsencrypt/live/~a/~a.pem"
            host (symbol->string file)))
  
  (define pronouun-cgit-nginx-configuration
    (nginx-server-configuration
     (root cgit)
     (server-name '("git.nouun.dev"
		    "www.git.nouun.dev"))
     (listen '("80"))
     (locations
      (list
       (nginx-location-configuration
	(uri "@cgit")
	(body '("fastcgi_param SCRIPT_FILENAME $document_root/lib/cgit/cgit.cgi;"
		"fastcgi_param PATH_INFO $uri;"
		"fastcgi_param QUERY_STRING $args;"
		"fastcgi_param HTTP_HOST $server_name;"
		"fastcgi_pass 127.0.0.1:9000;")))))
     (try-files (list "$uri" "@cgit"))
     (ssl-certificate (cert-path "git.nouun.dev"
                      'fullchain))
     (ssl-certificate-key (cert-path "git.karl.hallsby.com"
                          'privkey))))

  (define pronouun-cgit-service
    (service cgit-service-type
	     (cgit-configuration
	      (enable-commit-graph? #t)
	      (enable-html-serving? #t)
	      (repository-directory "/home/cgit/repositories")
	      (nocache? #t)
	      (nginx
               (list
                 pronouun-cgit-nginx-configuration)))))
#+END_SRC

**** Nginx

nginx

#+BEGIN_SRC scheme :tangle ../jayu/build/system/pronouun.scm
  (use-service-modules web)

  (define pronouun-website-nginx-configuration
    (nginx-server-configuration
     (server-name '("nouun.dev"
		    "www.nouun.dev"))
     (listen '("80"))))
     ;(ssl-certificate (cert-path "git.nouun.dev"
     ;                 'fullchain))
     ;(ssl-certificate-key (cert-path "git.karl.hallsby.com"
     ;                     'privkey))))

  (define pronouun-nginx-service
    (service nginx-service-type
	     (nginx-configuration
	      (server-blocks
	       (list pronouun-website-nginx-configuration)))))
#+END_SRC


**** Certbot

certbot

#+BEGIN_SRC scheme :tangle ../jayu/build/system/pronouun.scm
  (use-service-modules certbot)

  (define pronouun-certbot-nginx-deploy-hook
    (program-file
     "nginx-deploy-hook"
      #~(let ((pid (call-with-input-file "/var/run/nginx/pid" read)))
          (kill pid SIGHUP))))

  (define pronouun-certbot-service
    (service certbot-service-type
	     (certbot-configuration
	      (email "me@nouun.dev")
	      (certificates
	       (list
		(certificate-configuration
		 (name "Website")
		 (domains '("nouun.dev"
			    "www.nouun.dev"))
                 (deploy-hook
                    pronouun-certbot-nginx-deploy-hook))
		(certificate-configuration
		 (name "Website")
		 (domains '("git.nouun.dev"
			    "www.git.nouun.dev"))
                 (deploy-hook
                    pronouun-certbot-nginx-deploy-hook)))))))
#+END_SRC


**** DHCP

dhcp

#+BEGIN_SRC scheme :tangle ../jayu/build/system/pronouun.scm
  (use-service-modules networking)
  
  (define pronouun-dhcp-service
    (service dhcp-client-service-type))
#+END_SRC

**** OpenSSH

I use =openssh-sans-x= as there is no X11 server setup and
as such, OpenSSH doesn't need X11 support.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/pronouun.scm
  (use-service-modules ssh)
  (use-package-modules ssh)
  
  (define pronouun-ssh-service
    (service openssh-service-type
             (openssh-configuration
              (openssh openssh-sans-x)
              (password-authentication? #t)
              (permit-root-login #f))))
#+END_SRC


**** Base Services

Modify the default base services to do the following:

1) Nothing for now

#+BEGIN_SRC scheme :tangle ../jayu/build/system/pronouun.scm
  (define pronouun-base-services
    (append
     jayu-file-services
     %base-services))
#+END_SRC


**** Pronouun Services

Append all services into a single list.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/pronouun.scm
  (define pronouun-services
    (append (list pronouun-git-daemon-service
                  pronouun-fcgi-service
                  pronouun-cgit-service
                  pronouun-nginx-service
                  pronouun-certbot-service
                  pronouun-dhcp-service
                  pronouun-ssh-service)
            pronouun-base-services
            jayu-file-services))
#+END_SRC


*** Users

Users

#+BEGIN_SRC scheme :tangle ../jayu/build/system/pronouun.scm
  (define pronouun-users
    (list
      (user-account
       (name "git")
       (comment "git")
       (home-directory "/home/git")
       (group "users")
       (supplementary-groups
	 '("wheel" "netdev" "audio" "video"))
       (shell (file-append bash "/bin/bash")))))
#+END_SRC


*** System


**** File System

Mount root and boot partitions.

#+BEGIN_SRC scheme :tangle ../jayu/build/system/pronouun.scm
  (define pronouun-swap
    (list (uuid "61c2aeba-85ed-4e02-a227-027ecbd115f0")))

  (define pronouun-file-system
    (cons* (file-system
	     (mount-point "/")
	     (device
	       (uuid "b2b07395-cfd5-4133-86e2-5538eb0c0406"
		     'ext4))
	     (type "ext4"))
	   %base-file-systems))
#+END_SRC


**** System

Test

#+BEGIN_SRC scheme :tangle ../jayu/build/system/pronouun.scm
  (operating-system
      (inherit jayu-base-system)
      (host-name "pronouun")
      (users pronouun-users)
      (file-systems pronouun-file-system)

      (packages pronouun-packages)
      (services pronouun-services)

      (bootloader
	(bootloader-configuration
	  (bootloader grub-bootloader)
	  (targets (list "/dev/vda")))))
#+END_SRC
